server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-sreamtiash4qsy4h.us.auth0.com/
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or `validate` or `none` in prod
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG

account:
  service:
    url: http://localhost:8084

auth0:
  audience: https://mockbank/api

#      sudo kill -9 $(sudo lsof -t -i :5432)
#      docker run --name postgresql -e POSTGRES_PASSWORD=admin -p 5432:5432 -d postgres